#!/bin/bash
pkg_name=${@: -1}

export PKG_CONFIG_PATH=${TOOLCHAIN_PATH}/lib/pkgconfig
case $1 in
  --exists)
    pkg-config --exists $pkg_name
    ;;
  --cflags)
    echo $(pkg-config --cflags $pkg_name)
    ;;
  --libs)
    echo $(pkg-config --libs $pkg_name)
    ;;
  *)
    echo "FFmpeg pkg-config to build FFmpeg for Android!"
    ;;
esac
